### ISSUE TITLE
Low performance issues under parallel requests ?

### ISSUE THREAD

**Issue by abcfy2** [elizaOS/eliza#2311]
**Describe the bug**

I do a stress testing to `DirectClient`, but low performance. Here's the stress testing report: https://app.artillery.io/share/sh_973944e7b55ad120fef7a5e6c2a71980c176b5ab38b788baa7c3caa2a973f367

You can see almost all the requests timeout.

I guess `generateMessageResponse` will block event loop, so there can only be one concurrent request, but I'm not sure.

https://github.com/elizaOS/eliza/blob/89b6a190449a2e42aaeeef4cb6caec6448442614/packages/core/src/generation.ts#L1270-L1282

**To Reproduce**

Use eliza-starter to start DirectClient, set `OPENAI_API_URL` in `.env`:

```sh
OPENAI_API_URL=http://localhost:5002/v1
```

use [mockai](https://github.com/polly3d/mockai) to setup a mockai server, and set `data/contents.txt` to:
```json
{ "user": "agent1", "text": "Hi", "action": "IGNORE" }
```

start mockai and eliza-starter, then use artillery to run stress testing. Here's artillery config.yml:

```yaml
config:
  target: "http://localhost:3000"
  plugins:
    metrics-by-endpoint:
      useOnlyRequestNames: true
  http:
    timeout: 30
  phases:
    - duration: 120
      arrivalRate: 5
      rampTo: 50
      name: Ramp up load
    - duration: 720
      arrivalRate: 50
      maxVusers: 1000
      name: Sustained load
  variables:
    uuid:
      - 00acb7e1-c8db-0a34-9e4c-b0daadc3775b
      - 0d8ef5f1-d3df-0cbf-8e16-bd5ee0202e7c
      - 83ce34fa-65fa-07fa-926e-73eeb423a589
scenarios:
  - name: "POST /message"
    flow:
      - post:
          url: "/{{uuid}}/message"
          name: "POST /mint-request (onchain)"
          gzip: true
          headers:
            "Content-Type": "application/json"
          json:
            text: hi
```

Just post `{"text": "hi"}` to `http://localhost:3000/{uuid}/message`.
