### ISSUE TITLE
Running in cloud from docker image BUG

### ISSUE THREAD

**Issue by WNUMIK** [elizaOS/eliza#2343]
I have following error when running pnpm start in cloud in my docker container, my .env has CACHE_STORE=database

What can be wrong?
```
 ["⛔ Error: Invalid cache store: database # Defaults to database. Other available cache store: redis and filesystem or required configuration missing."] 

 ["✓ Successfully connected to PostgreSQL database"] 

 ⛔ ERRORS
   Error starting agents: 
   {} 
```

**Comment by Freytes** [comment]
What happens when you leave it blank?

**Comment by Freytes** [comment]
@WNUMIK there was a fix release in development can you try that?

**Comment by HashWarlock** [comment]
Run `pnpm build-docker` the docs aren't included in the docker image so this is the error you see

**Comment by WNUMIK** [comment]
> Run `pnpm build-docker` the docs aren't included in the docker image so this is the error you see

I tried that on new instance with arm64 and here is outcome:

```
 Tasks:    2 successful, 80 total
Cached:    0 cached, 80 total
  Time:    1m45.396s 
Failed:    @elizaos/client-telegram#build

 ERROR  run failed: command  exited (137)
 ELIFECYCLE  Command failed with exit code 137.
```

**Comment by WNUMIK** [comment]
> @WNUMIK there was a fix release in development can you try that?

Im doing new build with this fix will let know how it went

**Comment by WNUMIK** [comment]
I managed to run it but I have issue with env not sure why:

```
 ["⛔ Error: Telegram configuration validation failed:\nTELEGRAM_BOT_TOKEN: Required"] 

 ⛔ ERRORS
   Error starting agents: 
   {} 

```
I added .env to docker-compose-docs.yaml before building image, shouldn't it resolve .env issue?

```
services:
    docs:
        build:
            dockerfile: Dockerfile.docs
            context: .
            target: serve
        ports:
            - "3000:3000"
        env_file:
            - .env

```

**Comment by WNUMIK** [comment]
> I managed to run it but I have issue with env not sure why:
> 
> ```
>  ["⛔ Error: Telegram configuration validation failed:\nTELEGRAM_BOT_TOKEN: Required"] 
> 
>  ⛔ ERRORS
>    Error starting agents: 
>    {} 
> ```
> 
> I added .env to docker-compose-docs.yaml before building image, shouldn't it resolve .env issue? ofc I have `TELEGRAM_BOT_TOKEN` in .env so..
> 
> ```
> services:
>     docs:
>         build:
>             dockerfile: Dockerfile.docs
>             context: .
>             target: serve
>         ports:
>             - "3000:3000"
>         env_file:
>             - .env
> ```
> 
> also this persists:
> 
> ```
>  ⛔ ERRORS
>    Error starting agent for character Agent Bill the DeSci Guy: 
>    {} 
> 
>  ["⛔ Error: Invalid cache store: database # Defaults to database. Other available cache store: redis and filesystem or required configuration missing."] 
> 
>  ⛔ ERRORS
>    Error starting agents: 
>    {} 
> ```

Same error with `TELEGRAM_BOT_TOKEN: Required`

for this config:
```
services:
    eliza:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - eliza:/app/packages/client-twitter/src/tweetcache
            - eliza:/app/db.sqlite
        environment:
            - OPENAI_API_KEY=
            - CACHE_STORE=database
            - REDIS_URL=
            - POSTGRES_URL=
            - SERVER_PORT=3000
            - TELEGRAM_BOT_TOKEN=
            - COINMARKETCAP_API_KEY=
            - GIPHY_API_KEY=
            - COINGECKO_PRO_API_KEY=
            - COINGECKO_API_KEY=
            - AKASH_ENV=mainnet
            - AKASH_NET=https://raw.githubusercontent.com/ovrclk/net/master/mainnet
            - RPC_ENDPOINT=https://rpc.akashnet.net:443
            - AKASH_GAS_PRICES=0.025uakt
            - AKASH_GAS_ADJUSTMENT=1.5
            - AKASH_KEYRING_BACKEND=os
            - AKASH_FROM=default
            - AKASH_FEES=20000uakt
            - AKASH_DEPOSIT=500000uakt
            - AKASH_PRICING_API_URL=https://console-api.akash.network/v1/pricing
            - AKASH_DEFAULT_CPU=1000
            - AKASH_DEFAULT_MEMORY=1000000000
            - AKASH_DEFAULT_STORAGE=1000000000
            - AKASH_SDL=example.sdl.yml
            - AKASH_CLOSE_DEP=closeAll
            - AKASH_CLOSE_DSEQ=19729929
            - AKASH_PROVIDER_INFO=akash1ccktptfkvdc67msasmesuy5m7gpc76z75kukpz
            - AKASH_DEP_STATUS=dseq
            - AKASH_DEP_DSEQ=19729929
            - AKASH_GAS_OPERATION=close
            - AKASH_GAS_DSEQ=19729929
            - AKASH_MANIFEST_MODE=auto
            - AKASH_MANIFEST_VALIDATION_LEVEL=strict
        ports:
            - "3000:3000"
            - "5173:5173"
        restart: always

volumes:
    eliza:
```
