### ISSUE TITLE
Unexpected ERR_USE_AFTER_CLOSE error while running Eliza on Docker

### ISSUE THREAD

**Issue by ido567** [elizaOS/eliza#3692]
I'm trying to deploy the docker provided in `eliza-starter` repo for the first time with my new character. 
I was able to build the docker in my CI and run it in a container which looks ok.
At some point in the booting process of the service I get this weird `ERR_USE_AFTER_CLOSE` error which kills the process:

```
[2025-02-26 16:56:29] INFO: Buzz Feeley(2b6886f3-374d-0904-9c25-357b4472f50f) - Initializing AgentRuntime with options:
    character: "Buzz Feeley"
    modelProvider: "anthropic"
    characterModelProvider: "anthropic"
[2025-02-26 16:56:29] INFO: Buzz Feeley(2b6886f3-374d-0904-9c25-357b4472f50f) - Setting Model Provider:
    characterModelProvider: "anthropic"
    optsModelProvider: "anthropic"
    finalSelection: "anthropic"
[2025-02-26 16:56:29] INFO: Buzz Feeley(2b6886f3-374d-0904-9c25-357b4472f50f) - Selected model provider: anthropic
[2025-02-26 16:56:29] INFO: Buzz Feeley(2b6886f3-374d-0904-9c25-357b4472f50f) - Selected image model provider: anthropic
[2025-02-26 16:56:29] INFO: Buzz Feeley(2b6886f3-374d-0904-9c25-357b4472f50f) - Selected image vision model provider: anthropic
[2025-02-26 16:56:29] INFO: Initializing LlamaService...
[2025-02-26 16:56:29] ERROR: Unhandled error in startAgents:
    code: "ERR_USE_AFTER_CLOSE"
 ELIFECYCLE  Command failed with exit code 1.
```

I looked for the Eliza code and didn't find any related code, the only thing I found is [this resolved bug](https://github.com/elizaOS/eliza/issues/1168). 

This is my docker file (unchanged from the eliza-starter):
```
# Use a specific Node.js version for better reproducibility
FROM node:23.3.0-slim AS builder

# Install pnpm globally and install necessary build tools
RUN npm install -g pnpm@9.15.1 && \
    apt-get update && \
    apt-get install -y git python3 make g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set Python 3 as the default python
RUN ln -s /usr/bin/python3 /usr/bin/python

# Set the working directory
WORKDIR /app

# Copy package.json and other configuration files
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json ./

# Copy the rest of the application code
COPY ./src ./src
COPY ./characters ./characters

# Install dependencies and build the project
RUN pnpm install 
RUN pnpm build 

# Create dist directory and set permissions
RUN mkdir -p /app/dist && \
    chown -R node:node /app && \
    chmod -R 755 /app

# Switch to node user
USER node

# Create a new stage for the final image
FROM node:23.3.0-slim

# Install runtime dependencies if needed
RUN npm install -g pnpm@9.15.1
RUN apt-get update && \
    apt-get install -y git python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy built artifacts and production dependencies from the builder stage
COPY --from=builder /app/package.json /app/
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/src /app/src
COPY --from=builder /app/characters /app/characters
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/tsconfig.json /app/
COPY --from=builder /app/pnpm-lock.yaml /app/

EXPOSE 3000
# Set the command to run the application
CMD ["pnpm", "start", "--non-interactive"]
```

And this is the container configuration: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliza-service
  namespace: eliza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eliza-service
  template:
    metadata:
      labels:
        app: eliza-service
    spec:
      serviceAccountName: eliza-sa
      containers:
      - name: my-application
        image: REDUCTED
        command: ["pnpm", "start", "--character=./characters/buzzfeeley.character.json", "--non-interactive"]
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: '3000'
        ports:
        - containerPort: 3000
```

Package.json:
```
{
  "name": "@elizaos/eliza-starter",
  "version": "0.1.9",
  "main": "src/index.ts",
  "type": "module",
  "scripts": {
    "build": "tsup src/index.ts --format esm --dts",
    "start": "tsc && node --loader ts-node/esm src/index.ts",
    "clean": "./scripts/clean.sh",
    "start:service:all": "pm2 start pnpm --name=\"all\" --restart-delay=3000 --max-restarts=10 -- run start:all",
    "stop:service:all": "pm2 stop all"
  },
  "dependencies": {
    "@elizaos/adapter-postgres": "0.1.9",
    "@elizaos/adapter-sqlite": "0.1.9",
    "@elizaos/client-auto": "0.1.9",
    "@elizaos/client-direct": "0.1.9",
    "@elizaos/client-discord": "0.1.9",
    "@elizaos/client-telegram": "0.1.9",
    "@elizaos/client-twitter": "0.1.9",
    "@elizaos/core": "0.1.9",
    "@elizaos/plugin-bootstrap": "0.1.9",
    "@elizaos/plugin-image-generation": "0.1.9",
    "@elizaos/plugin-node": "0.1.9",
    "@elizaos/plugin-solana": "0.1.9",
    "@elizaos/plugin-starknet": "0.1.9",
    "@tavily/core": "0.0.2",
    "amqplib": "0.10.5",
    "better-sqlite3": "11.5.0",
    "dotenv": "^16.4.7",
    "fs": "0.0.1-security",
    "net": "1.0.2",
    "path": "0.12.7",
    "readline": "1.3.0",
    "url": "0.11.4",
    "ws": "8.18.0",
    "yargs": "17.7.2"
  },
  "engines": {
    "node": ">=22"
  },
  "pnpm": {
    "overrides": {
      "onnxruntime-node": "1.20.0"
    },
    "ignoredBuiltDependencies": [
      "@discordjs/opus",
      "@elizaos/plugin-node",
      "bigint-buffer",
      "bufferutil",
      "canvas",
      "es5-ext",
      "esbuild",
      "ffmpeg-static",
      "keccak",
      "node-hid",
      "node-llama-cpp",
      "onnxruntime-node",
      "protobufjs",
      "puppeteer",
      "secp256k1",
      "sharp",
      "sodium-native",
      "usb",
      "utf-8-validate",
      "wtf_wikipedia",
      "youtube-dl-exec"
    ],
    "onlyBuiltDependencies": [
      "better-sqlite3"
    ]
  },
  "devDependencies": {
    "pm2": "5.4.3",
    "ts-node": "10.9.2",
    "tsup": "8.3.5",
    "typescript": "5.6.3"
  }
}
```
